// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGES_EVENT_H_
#define FLATBUFFERS_GENERATED_MESSAGES_EVENT_H_

#include "flatbuffers/flatbuffers.h"

namespace event {

struct Message;
struct MessageBuilder;

struct Echo;
struct EchoBuilder;

struct UserEvent;
struct UserEventBuilder;

struct CursorEvent;

struct Point;

struct Color;

struct ObjectUpdateEvent;
struct ObjectUpdateEventBuilder;

struct ObjectAddPointsEvent;
struct ObjectAddPointsEventBuilder;

struct ObjectDeleteEvent;
struct ObjectDeleteEventBuilder;

enum Event {
  Event_NONE = 0,
  Event_CursorEvent = 1,
  Event_ObjectUpdateEvent = 2,
  Event_ObjectAddPointsEvent = 3,
  Event_ObjectDeleteEvent = 4,
  Event_UserEvent = 5,
  Event_Echo = 6,
  Event_MIN = Event_NONE,
  Event_MAX = Event_Echo
};

inline const Event (&EnumValuesEvent())[7] {
  static const Event values[] = {
    Event_NONE,
    Event_CursorEvent,
    Event_ObjectUpdateEvent,
    Event_ObjectAddPointsEvent,
    Event_ObjectDeleteEvent,
    Event_UserEvent,
    Event_Echo
  };
  return values;
}

inline const char * const *EnumNamesEvent() {
  static const char * const names[8] = {
    "NONE",
    "CursorEvent",
    "ObjectUpdateEvent",
    "ObjectAddPointsEvent",
    "ObjectDeleteEvent",
    "UserEvent",
    "Echo",
    nullptr
  };
  return names;
}

inline const char *EnumNameEvent(Event e) {
  if (flatbuffers::IsOutRange(e, Event_NONE, Event_Echo)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEvent()[index];
}

template<typename T> struct EventTraits {
  static const Event enum_value = Event_NONE;
};

template<> struct EventTraits<event::CursorEvent> {
  static const Event enum_value = Event_CursorEvent;
};

template<> struct EventTraits<event::ObjectUpdateEvent> {
  static const Event enum_value = Event_ObjectUpdateEvent;
};

template<> struct EventTraits<event::ObjectAddPointsEvent> {
  static const Event enum_value = Event_ObjectAddPointsEvent;
};

template<> struct EventTraits<event::ObjectDeleteEvent> {
  static const Event enum_value = Event_ObjectDeleteEvent;
};

template<> struct EventTraits<event::UserEvent> {
  static const Event enum_value = Event_UserEvent;
};

template<> struct EventTraits<event::Echo> {
  static const Event enum_value = Event_Echo;
};

bool VerifyEvent(flatbuffers::Verifier &verifier, const void *obj, Event type);
bool VerifyEventVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

enum ObjectType {
  ObjectType_Line = 0,
  ObjectType_PolyLine = 1,
  ObjectType_Rectangle = 2,
  ObjectType_Circle = 3,
  ObjectType_MIN = ObjectType_Line,
  ObjectType_MAX = ObjectType_Circle
};

inline const ObjectType (&EnumValuesObjectType())[4] {
  static const ObjectType values[] = {
    ObjectType_Line,
    ObjectType_PolyLine,
    ObjectType_Rectangle,
    ObjectType_Circle
  };
  return values;
}

inline const char * const *EnumNamesObjectType() {
  static const char * const names[5] = {
    "Line",
    "PolyLine",
    "Rectangle",
    "Circle",
    nullptr
  };
  return names;
}

inline const char *EnumNameObjectType(ObjectType e) {
  if (flatbuffers::IsOutRange(e, ObjectType_Line, ObjectType_Circle)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesObjectType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) CursorEvent FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t x_;
  int32_t y_;
  uint32_t uid_;

 public:
  CursorEvent() {
    memset(static_cast<void *>(this), 0, sizeof(CursorEvent));
  }
  CursorEvent(int32_t _x, int32_t _y, uint32_t _uid)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        uid_(flatbuffers::EndianScalar(_uid)) {
  }
  int32_t x() const {
    return flatbuffers::EndianScalar(x_);
  }
  int32_t y() const {
    return flatbuffers::EndianScalar(y_);
  }
  uint32_t uid() const {
    return flatbuffers::EndianScalar(uid_);
  }
};
FLATBUFFERS_STRUCT_END(CursorEvent, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Point FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t x_;
  uint16_t y_;

 public:
  Point() {
    memset(static_cast<void *>(this), 0, sizeof(Point));
  }
  Point(uint16_t _x, uint16_t _y)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)) {
  }
  uint16_t x() const {
    return flatbuffers::EndianScalar(x_);
  }
  uint16_t y() const {
    return flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Point, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Color FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t r_;
  uint8_t g_;
  uint8_t b_;

 public:
  Color() {
    memset(static_cast<void *>(this), 0, sizeof(Color));
  }
  Color(uint8_t _r, uint8_t _g, uint8_t _b)
      : r_(flatbuffers::EndianScalar(_r)),
        g_(flatbuffers::EndianScalar(_g)),
        b_(flatbuffers::EndianScalar(_b)) {
  }
  uint8_t r() const {
    return flatbuffers::EndianScalar(r_);
  }
  uint8_t g() const {
    return flatbuffers::EndianScalar(g_);
  }
  uint8_t b() const {
    return flatbuffers::EndianScalar(b_);
  }
};
FLATBUFFERS_STRUCT_END(Color, 3);

struct Message FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EVENT_TYPE = 4,
    VT_EVENT = 6
  };
  event::Event event_type() const {
    return static_cast<event::Event>(GetField<uint8_t>(VT_EVENT_TYPE, 0));
  }
  const void *event() const {
    return GetPointer<const void *>(VT_EVENT);
  }
  template<typename T> const T *event_as() const;
  const event::CursorEvent *event_as_CursorEvent() const {
    return event_type() == event::Event_CursorEvent ? static_cast<const event::CursorEvent *>(event()) : nullptr;
  }
  const event::ObjectUpdateEvent *event_as_ObjectUpdateEvent() const {
    return event_type() == event::Event_ObjectUpdateEvent ? static_cast<const event::ObjectUpdateEvent *>(event()) : nullptr;
  }
  const event::ObjectAddPointsEvent *event_as_ObjectAddPointsEvent() const {
    return event_type() == event::Event_ObjectAddPointsEvent ? static_cast<const event::ObjectAddPointsEvent *>(event()) : nullptr;
  }
  const event::ObjectDeleteEvent *event_as_ObjectDeleteEvent() const {
    return event_type() == event::Event_ObjectDeleteEvent ? static_cast<const event::ObjectDeleteEvent *>(event()) : nullptr;
  }
  const event::UserEvent *event_as_UserEvent() const {
    return event_type() == event::Event_UserEvent ? static_cast<const event::UserEvent *>(event()) : nullptr;
  }
  const event::Echo *event_as_Echo() const {
    return event_type() == event::Event_Echo ? static_cast<const event::Echo *>(event()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_EVENT_TYPE) &&
           VerifyOffset(verifier, VT_EVENT) &&
           VerifyEvent(verifier, event(), event_type()) &&
           verifier.EndTable();
  }
};

template<> inline const event::CursorEvent *Message::event_as<event::CursorEvent>() const {
  return event_as_CursorEvent();
}

template<> inline const event::ObjectUpdateEvent *Message::event_as<event::ObjectUpdateEvent>() const {
  return event_as_ObjectUpdateEvent();
}

template<> inline const event::ObjectAddPointsEvent *Message::event_as<event::ObjectAddPointsEvent>() const {
  return event_as_ObjectAddPointsEvent();
}

template<> inline const event::ObjectDeleteEvent *Message::event_as<event::ObjectDeleteEvent>() const {
  return event_as_ObjectDeleteEvent();
}

template<> inline const event::UserEvent *Message::event_as<event::UserEvent>() const {
  return event_as_UserEvent();
}

template<> inline const event::Echo *Message::event_as<event::Echo>() const {
  return event_as_Echo();
}

struct MessageBuilder {
  typedef Message Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_event_type(event::Event event_type) {
    fbb_.AddElement<uint8_t>(Message::VT_EVENT_TYPE, static_cast<uint8_t>(event_type), 0);
  }
  void add_event(flatbuffers::Offset<void> event) {
    fbb_.AddOffset(Message::VT_EVENT, event);
  }
  explicit MessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MessageBuilder &operator=(const MessageBuilder &);
  flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline flatbuffers::Offset<Message> CreateMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    event::Event event_type = event::Event_NONE,
    flatbuffers::Offset<void> event = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_event(event);
  builder_.add_event_type(event_type);
  return builder_.Finish();
}

struct Echo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef EchoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TIME = 6,
    VT_PAYLOAD = 8
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  uint32_t time() const {
    return GetField<uint32_t>(VT_TIME, 0);
  }
  const flatbuffers::String *payload() const {
    return GetPointer<const flatbuffers::String *>(VT_PAYLOAD);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyField<uint32_t>(verifier, VT_TIME) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyString(payload()) &&
           verifier.EndTable();
  }
};

struct EchoBuilder {
  typedef Echo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(Echo::VT_ID, id, 0);
  }
  void add_time(uint32_t time) {
    fbb_.AddElement<uint32_t>(Echo::VT_TIME, time, 0);
  }
  void add_payload(flatbuffers::Offset<flatbuffers::String> payload) {
    fbb_.AddOffset(Echo::VT_PAYLOAD, payload);
  }
  explicit EchoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  EchoBuilder &operator=(const EchoBuilder &);
  flatbuffers::Offset<Echo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Echo>(end);
    return o;
  }
};

inline flatbuffers::Offset<Echo> CreateEcho(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    uint32_t time = 0,
    flatbuffers::Offset<flatbuffers::String> payload = 0) {
  EchoBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_time(time);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<Echo> CreateEchoDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    uint32_t time = 0,
    const char *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateString(payload) : 0;
  return event::CreateEcho(
      _fbb,
      id,
      time,
      payload__);
}

struct UserEvent FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UserEventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UID = 4,
    VT_NAME = 6
  };
  uint32_t uid() const {
    return GetField<uint32_t>(VT_UID, 0);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_UID) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct UserEventBuilder {
  typedef UserEvent Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_uid(uint32_t uid) {
    fbb_.AddElement<uint32_t>(UserEvent::VT_UID, uid, 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(UserEvent::VT_NAME, name);
  }
  explicit UserEventBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  UserEventBuilder &operator=(const UserEventBuilder &);
  flatbuffers::Offset<UserEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UserEvent>(end);
    return o;
  }
};

inline flatbuffers::Offset<UserEvent> CreateUserEvent(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t uid = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0) {
  UserEventBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_uid(uid);
  return builder_.Finish();
}

inline flatbuffers::Offset<UserEvent> CreateUserEventDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t uid = 0,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return event::CreateUserEvent(
      _fbb,
      uid,
      name__);
}

struct ObjectUpdateEvent FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ObjectUpdateEventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_COLOR = 8,
    VT_POINTS = 10
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  event::ObjectType type() const {
    return static_cast<event::ObjectType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const event::Color *color() const {
    return GetStruct<const event::Color *>(VT_COLOR);
  }
  const flatbuffers::Vector<const event::Point *> *points() const {
    return GetPointer<const flatbuffers::Vector<const event::Point *> *>(VT_POINTS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyField<int8_t>(verifier, VT_TYPE) &&
           VerifyField<event::Color>(verifier, VT_COLOR) &&
           VerifyOffset(verifier, VT_POINTS) &&
           verifier.VerifyVector(points()) &&
           verifier.EndTable();
  }
};

struct ObjectUpdateEventBuilder {
  typedef ObjectUpdateEvent Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(ObjectUpdateEvent::VT_ID, id, 0);
  }
  void add_type(event::ObjectType type) {
    fbb_.AddElement<int8_t>(ObjectUpdateEvent::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_color(const event::Color *color) {
    fbb_.AddStruct(ObjectUpdateEvent::VT_COLOR, color);
  }
  void add_points(flatbuffers::Offset<flatbuffers::Vector<const event::Point *>> points) {
    fbb_.AddOffset(ObjectUpdateEvent::VT_POINTS, points);
  }
  explicit ObjectUpdateEventBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ObjectUpdateEventBuilder &operator=(const ObjectUpdateEventBuilder &);
  flatbuffers::Offset<ObjectUpdateEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ObjectUpdateEvent>(end);
    return o;
  }
};

inline flatbuffers::Offset<ObjectUpdateEvent> CreateObjectUpdateEvent(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    event::ObjectType type = event::ObjectType_Line,
    const event::Color *color = 0,
    flatbuffers::Offset<flatbuffers::Vector<const event::Point *>> points = 0) {
  ObjectUpdateEventBuilder builder_(_fbb);
  builder_.add_points(points);
  builder_.add_color(color);
  builder_.add_id(id);
  builder_.add_type(type);
  return builder_.Finish();
}

inline flatbuffers::Offset<ObjectUpdateEvent> CreateObjectUpdateEventDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    event::ObjectType type = event::ObjectType_Line,
    const event::Color *color = 0,
    const std::vector<event::Point> *points = nullptr) {
  auto points__ = points ? _fbb.CreateVectorOfStructs<event::Point>(*points) : 0;
  return event::CreateObjectUpdateEvent(
      _fbb,
      id,
      type,
      color,
      points__);
}

struct ObjectAddPointsEvent FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ObjectAddPointsEventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_POINTS = 6
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const flatbuffers::Vector<const event::Point *> *points() const {
    return GetPointer<const flatbuffers::Vector<const event::Point *> *>(VT_POINTS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyOffset(verifier, VT_POINTS) &&
           verifier.VerifyVector(points()) &&
           verifier.EndTable();
  }
};

struct ObjectAddPointsEventBuilder {
  typedef ObjectAddPointsEvent Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(ObjectAddPointsEvent::VT_ID, id, 0);
  }
  void add_points(flatbuffers::Offset<flatbuffers::Vector<const event::Point *>> points) {
    fbb_.AddOffset(ObjectAddPointsEvent::VT_POINTS, points);
  }
  explicit ObjectAddPointsEventBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ObjectAddPointsEventBuilder &operator=(const ObjectAddPointsEventBuilder &);
  flatbuffers::Offset<ObjectAddPointsEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ObjectAddPointsEvent>(end);
    return o;
  }
};

inline flatbuffers::Offset<ObjectAddPointsEvent> CreateObjectAddPointsEvent(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    flatbuffers::Offset<flatbuffers::Vector<const event::Point *>> points = 0) {
  ObjectAddPointsEventBuilder builder_(_fbb);
  builder_.add_points(points);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<ObjectAddPointsEvent> CreateObjectAddPointsEventDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    const std::vector<event::Point> *points = nullptr) {
  auto points__ = points ? _fbb.CreateVectorOfStructs<event::Point>(*points) : 0;
  return event::CreateObjectAddPointsEvent(
      _fbb,
      id,
      points__);
}

struct ObjectDeleteEvent FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ObjectDeleteEventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           verifier.EndTable();
  }
};

struct ObjectDeleteEventBuilder {
  typedef ObjectDeleteEvent Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(ObjectDeleteEvent::VT_ID, id, 0);
  }
  explicit ObjectDeleteEventBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ObjectDeleteEventBuilder &operator=(const ObjectDeleteEventBuilder &);
  flatbuffers::Offset<ObjectDeleteEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ObjectDeleteEvent>(end);
    return o;
  }
};

inline flatbuffers::Offset<ObjectDeleteEvent> CreateObjectDeleteEvent(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  ObjectDeleteEventBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

inline bool VerifyEvent(flatbuffers::Verifier &verifier, const void *obj, Event type) {
  switch (type) {
    case Event_NONE: {
      return true;
    }
    case Event_CursorEvent: {
      return verifier.Verify<event::CursorEvent>(static_cast<const uint8_t *>(obj), 0);
    }
    case Event_ObjectUpdateEvent: {
      auto ptr = reinterpret_cast<const event::ObjectUpdateEvent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Event_ObjectAddPointsEvent: {
      auto ptr = reinterpret_cast<const event::ObjectAddPointsEvent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Event_ObjectDeleteEvent: {
      auto ptr = reinterpret_cast<const event::ObjectDeleteEvent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Event_UserEvent: {
      auto ptr = reinterpret_cast<const event::UserEvent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Event_Echo: {
      auto ptr = reinterpret_cast<const event::Echo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyEventVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyEvent(
        verifier,  values->Get(i), types->GetEnum<Event>(i))) {
      return false;
    }
  }
  return true;
}

inline const event::Message *GetMessage(const void *buf) {
  return flatbuffers::GetRoot<event::Message>(buf);
}

inline const event::Message *GetSizePrefixedMessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<event::Message>(buf);
}

inline bool VerifyMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<event::Message>(nullptr);
}

inline bool VerifySizePrefixedMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<event::Message>(nullptr);
}

inline void FinishMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<event::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<event::Message> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace event

#endif  // FLATBUFFERS_GENERATED_MESSAGES_EVENT_H_
