#!/bin/bash

cd apps/etherpaint/cmake-build-debug/

killall paper

if [ "$1" == "make" ] ; then
    make -j32 || exit 1
fi

cd ../conf
../cmake-build-debug/paper etherpaint.ini &


wait
echo "BACKGROUND DONE!"



