#!/bin/bash
killall -9 restbed_test

cd build
cmake .. || exit 1
cmake --build . -v -- -j10 || exit 1
echo "GO.."
./restbed_test &

# for bla in `seq 0 1000`; do curl -s http://localhost:1984/stream >/dev/null & done
# sleep 10
# killall -9 restbed_test

# curl -v http://localhost:1984/events
# curl -d '["12321",[{"bla":1},{"bla":2}]]' http://localhost:1984/send -v 
# curl  -v http://localhost:3000   >/dev/null
curl  -v http://localhost:3000/edit.html

echo
echo "CURL DONE"
wait
echo "BACKGROUND DONE!"



