#!/bin/bash
set -e

#make?
if echo "$@" | grep make; then
    pushd apps/etherpaint/cmake-build-debug/
    make -j32 
    popd
fi


if echo "$@" | grep pack; then
  #webpack
  pushd apps/etherpaint/wwwdir
  yarn install
  echo "Webpack.."
  npx webpack
  popd
fi

if echo "$@" | grep test; then
  #webpack test scripts
  pushd apps/etherpaint/wwwdir/test
  yarn install
  echo "Webpack test scripts.."
  npx webpack
  popd
fi


#run
cd apps/etherpaint/conf
killall paper || true
../cmake-build-debug/paper etherpaint.ini &


wait
echo "BACKGROUND DONE!"



