// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var event = event || {};

/**
 * @enum {number}
 */
event.EventUnion = {
  NONE: 0,
  CursorEvent: 1,
  ObjectUpdateEvent: 2,
  ObjectAddPointsEvent: 3,
  ObjectDeleteEvent: 4,
  UserEvent: 5,
  Echo: 6
};

/**
 * @enum {string}
 */
event.EventUnionName = {
  '0': 'NONE',
  '1': 'CursorEvent',
  '2': 'ObjectUpdateEvent',
  '3': 'ObjectAddPointsEvent',
  '4': 'ObjectDeleteEvent',
  '5': 'UserEvent',
  '6': 'Echo'
};

/**
 * @enum {number}
 */
event.ObjectType = {
  Line: 0,
  PolyLine: 1,
  Rectangle: 2,
  Circle: 3
};

/**
 * @enum {string}
 */
event.ObjectTypeName = {
  '0': 'Line',
  '1': 'PolyLine',
  '2': 'Rectangle',
  '3': 'Circle'
};

/**
 * @constructor
 */
event.Message = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {event.Message}
 */
event.Message.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.Message=} obj
 * @returns {event.Message}
 */
event.Message.getRootAsMessage = function(bb, obj) {
  return (obj || new event.Message).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.Message=} obj
 * @returns {event.Message}
 */
event.Message.getSizePrefixedRootAsMessage = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new event.Message).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {event.EventUnion}
 */
event.Message.prototype.eventType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {event.EventUnion} */ (this.bb.readUint8(this.bb_pos + offset)) : event.EventUnion.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
event.Message.prototype.event = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @returns {number}
 */
event.Message.prototype.kut = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 123;
};

/**
 * @param {flatbuffers.Builder} builder
 */
event.Message.startMessage = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {event.EventUnion} eventType
 */
event.Message.addEventType = function(builder, eventType) {
  builder.addFieldInt8(0, eventType, event.EventUnion.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} eventOffset
 */
event.Message.addEvent = function(builder, eventOffset) {
  builder.addFieldOffset(1, eventOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} kut
 */
event.Message.addKut = function(builder, kut) {
  builder.addFieldInt32(2, kut, 123);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
event.Message.endMessage = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
event.Message.finishMessageBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
event.Message.finishSizePrefixedMessageBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {event.EventUnion} eventType
 * @param {flatbuffers.Offset} eventOffset
 * @param {number} kut
 * @returns {flatbuffers.Offset}
 */
event.Message.createMessage = function(builder, eventType, eventOffset, kut) {
  event.Message.startMessage(builder);
  event.Message.addEventType(builder, eventType);
  event.Message.addEvent(builder, eventOffset);
  event.Message.addKut(builder, kut);
  return event.Message.endMessage(builder);
}

/**
 * @constructor
 */
event.Echo = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {event.Echo}
 */
event.Echo.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.Echo=} obj
 * @returns {event.Echo}
 */
event.Echo.getRootAsEcho = function(bb, obj) {
  return (obj || new event.Echo).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.Echo=} obj
 * @returns {event.Echo}
 */
event.Echo.getSizePrefixedRootAsEcho = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new event.Echo).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
event.Echo.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
event.Echo.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
event.Echo.prototype.payload = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
event.Echo.startEcho = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
event.Echo.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} time
 */
event.Echo.addTime = function(builder, time) {
  builder.addFieldInt32(1, time, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} payloadOffset
 */
event.Echo.addPayload = function(builder, payloadOffset) {
  builder.addFieldOffset(2, payloadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
event.Echo.endEcho = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 * @param {number} time
 * @param {flatbuffers.Offset} payloadOffset
 * @returns {flatbuffers.Offset}
 */
event.Echo.createEcho = function(builder, id, time, payloadOffset) {
  event.Echo.startEcho(builder);
  event.Echo.addId(builder, id);
  event.Echo.addTime(builder, time);
  event.Echo.addPayload(builder, payloadOffset);
  return event.Echo.endEcho(builder);
}

/**
 * @constructor
 */
event.UserEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {event.UserEvent}
 */
event.UserEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.UserEvent=} obj
 * @returns {event.UserEvent}
 */
event.UserEvent.getRootAsUserEvent = function(bb, obj) {
  return (obj || new event.UserEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.UserEvent=} obj
 * @returns {event.UserEvent}
 */
event.UserEvent.getSizePrefixedRootAsUserEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new event.UserEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
event.UserEvent.prototype.uid = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
event.UserEvent.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
event.UserEvent.startUserEvent = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} uid
 */
event.UserEvent.addUid = function(builder, uid) {
  builder.addFieldInt32(0, uid, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
event.UserEvent.addName = function(builder, nameOffset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
event.UserEvent.endUserEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} uid
 * @param {flatbuffers.Offset} nameOffset
 * @returns {flatbuffers.Offset}
 */
event.UserEvent.createUserEvent = function(builder, uid, nameOffset) {
  event.UserEvent.startUserEvent(builder);
  event.UserEvent.addUid(builder, uid);
  event.UserEvent.addName(builder, nameOffset);
  return event.UserEvent.endUserEvent(builder);
}

/**
 * @constructor
 */
event.CursorEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {event.CursorEvent}
 */
event.CursorEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
event.CursorEvent.prototype.x = function() {
  return this.bb.readInt32(this.bb_pos);
};

/**
 * @returns {number}
 */
event.CursorEvent.prototype.y = function() {
  return this.bb.readInt32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
event.CursorEvent.prototype.uid = function() {
  return this.bb.readUint32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @param {number} uid
 * @returns {flatbuffers.Offset}
 */
event.CursorEvent.createCursorEvent = function(builder, x, y, uid) {
  builder.prep(4, 12);
  builder.writeInt32(uid);
  builder.writeInt32(y);
  builder.writeInt32(x);
  return builder.offset();
};

/**
 * @constructor
 */
event.Point = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {event.Point}
 */
event.Point.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
event.Point.prototype.x = function() {
  return this.bb.readUint16(this.bb_pos);
};

/**
 * @returns {number}
 */
event.Point.prototype.y = function() {
  return this.bb.readUint16(this.bb_pos + 2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @returns {flatbuffers.Offset}
 */
event.Point.createPoint = function(builder, x, y) {
  builder.prep(2, 4);
  builder.writeInt16(y);
  builder.writeInt16(x);
  return builder.offset();
};

/**
 * @constructor
 */
event.Color = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {event.Color}
 */
event.Color.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
event.Color.prototype.r = function() {
  return this.bb.readUint8(this.bb_pos);
};

/**
 * @returns {number}
 */
event.Color.prototype.g = function() {
  return this.bb.readUint8(this.bb_pos + 1);
};

/**
 * @returns {number}
 */
event.Color.prototype.b = function() {
  return this.bb.readUint8(this.bb_pos + 2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} r
 * @param {number} g
 * @param {number} b
 * @returns {flatbuffers.Offset}
 */
event.Color.createColor = function(builder, r, g, b) {
  builder.prep(1, 3);
  builder.writeInt8(b);
  builder.writeInt8(g);
  builder.writeInt8(r);
  return builder.offset();
};

/**
 * @constructor
 */
event.ObjectUpdateEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {event.ObjectUpdateEvent}
 */
event.ObjectUpdateEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.ObjectUpdateEvent=} obj
 * @returns {event.ObjectUpdateEvent}
 */
event.ObjectUpdateEvent.getRootAsObjectUpdateEvent = function(bb, obj) {
  return (obj || new event.ObjectUpdateEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.ObjectUpdateEvent=} obj
 * @returns {event.ObjectUpdateEvent}
 */
event.ObjectUpdateEvent.getSizePrefixedRootAsObjectUpdateEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new event.ObjectUpdateEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
event.ObjectUpdateEvent.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {event.ObjectType}
 */
event.ObjectUpdateEvent.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {event.ObjectType} */ (this.bb.readInt8(this.bb_pos + offset)) : event.ObjectType.Line;
};

/**
 * @param {event.Color=} obj
 * @returns {event.Color|null}
 */
event.ObjectUpdateEvent.prototype.color = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new event.Color).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {number} index
 * @param {event.Point=} obj
 * @returns {event.Point}
 */
event.ObjectUpdateEvent.prototype.points = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new event.Point).__init(this.bb.__vector(this.bb_pos + offset) + index * 4, this.bb) : null;
};

/**
 * @returns {number}
 */
event.ObjectUpdateEvent.prototype.pointsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
event.ObjectUpdateEvent.startObjectUpdateEvent = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
event.ObjectUpdateEvent.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {event.ObjectType} type
 */
event.ObjectUpdateEvent.addType = function(builder, type) {
  builder.addFieldInt8(1, type, event.ObjectType.Line);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} colorOffset
 */
event.ObjectUpdateEvent.addColor = function(builder, colorOffset) {
  builder.addFieldStruct(2, colorOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} pointsOffset
 */
event.ObjectUpdateEvent.addPoints = function(builder, pointsOffset) {
  builder.addFieldOffset(3, pointsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
event.ObjectUpdateEvent.startPointsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
event.ObjectUpdateEvent.endObjectUpdateEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 * @param {event.ObjectType} type
 * @param {flatbuffers.Offset} colorOffset
 * @param {flatbuffers.Offset} pointsOffset
 * @returns {flatbuffers.Offset}
 */
event.ObjectUpdateEvent.createObjectUpdateEvent = function(builder, id, type, colorOffset, pointsOffset) {
  event.ObjectUpdateEvent.startObjectUpdateEvent(builder);
  event.ObjectUpdateEvent.addId(builder, id);
  event.ObjectUpdateEvent.addType(builder, type);
  event.ObjectUpdateEvent.addColor(builder, colorOffset);
  event.ObjectUpdateEvent.addPoints(builder, pointsOffset);
  return event.ObjectUpdateEvent.endObjectUpdateEvent(builder);
}

/**
 * @constructor
 */
event.ObjectAddPointsEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {event.ObjectAddPointsEvent}
 */
event.ObjectAddPointsEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.ObjectAddPointsEvent=} obj
 * @returns {event.ObjectAddPointsEvent}
 */
event.ObjectAddPointsEvent.getRootAsObjectAddPointsEvent = function(bb, obj) {
  return (obj || new event.ObjectAddPointsEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.ObjectAddPointsEvent=} obj
 * @returns {event.ObjectAddPointsEvent}
 */
event.ObjectAddPointsEvent.getSizePrefixedRootAsObjectAddPointsEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new event.ObjectAddPointsEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
event.ObjectAddPointsEvent.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {event.Point=} obj
 * @returns {event.Point}
 */
event.ObjectAddPointsEvent.prototype.points = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new event.Point).__init(this.bb.__vector(this.bb_pos + offset) + index * 4, this.bb) : null;
};

/**
 * @returns {number}
 */
event.ObjectAddPointsEvent.prototype.pointsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
event.ObjectAddPointsEvent.startObjectAddPointsEvent = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
event.ObjectAddPointsEvent.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} pointsOffset
 */
event.ObjectAddPointsEvent.addPoints = function(builder, pointsOffset) {
  builder.addFieldOffset(1, pointsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
event.ObjectAddPointsEvent.startPointsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
event.ObjectAddPointsEvent.endObjectAddPointsEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 * @param {flatbuffers.Offset} pointsOffset
 * @returns {flatbuffers.Offset}
 */
event.ObjectAddPointsEvent.createObjectAddPointsEvent = function(builder, id, pointsOffset) {
  event.ObjectAddPointsEvent.startObjectAddPointsEvent(builder);
  event.ObjectAddPointsEvent.addId(builder, id);
  event.ObjectAddPointsEvent.addPoints(builder, pointsOffset);
  return event.ObjectAddPointsEvent.endObjectAddPointsEvent(builder);
}

/**
 * @constructor
 */
event.ObjectDeleteEvent = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {event.ObjectDeleteEvent}
 */
event.ObjectDeleteEvent.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.ObjectDeleteEvent=} obj
 * @returns {event.ObjectDeleteEvent}
 */
event.ObjectDeleteEvent.getRootAsObjectDeleteEvent = function(bb, obj) {
  return (obj || new event.ObjectDeleteEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {event.ObjectDeleteEvent=} obj
 * @returns {event.ObjectDeleteEvent}
 */
event.ObjectDeleteEvent.getSizePrefixedRootAsObjectDeleteEvent = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new event.ObjectDeleteEvent).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
event.ObjectDeleteEvent.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
event.ObjectDeleteEvent.startObjectDeleteEvent = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
event.ObjectDeleteEvent.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
event.ObjectDeleteEvent.endObjectDeleteEvent = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 * @returns {flatbuffers.Offset}
 */
event.ObjectDeleteEvent.createObjectDeleteEvent = function(builder, id) {
  event.ObjectDeleteEvent.startObjectDeleteEvent(builder);
  event.ObjectDeleteEvent.addId(builder, id);
  return event.ObjectDeleteEvent.endObjectDeleteEvent(builder);
}

// Exports for Node.js and RequireJS
this.event = event;
